name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install pyinstaller
      run: pip install pyinstaller
    - name: Install rpm
      run: sudo apt-get install -y rpm
    - name: Install gcovr
      run: sudo apt-get install -y gcovr
    - name: Clone libcheck
      run: git clone https://github.com/libcheck/check.git
    - name: Install libcheck
      run: cd check/ && autoreconf --install && ./configure && make && sudo make install && sudo ldconfig
    - name: make
      run: cd lib/ && make
    - name: make coverage
      run: cd lib/ && make coverage
    - name: Print result tap
      if: always()
      run: cat lib/tests/*.tap
    - name: Build rpm package
      run: ./build.sh
    - name: Archive rpm package
      uses: actions/upload-artifact@v3
      with:
        name: rpm-package
        path: release/*.rpm
